package mx.model;
// Generated 24/09/2020 09:46:10 PM by Hibernate Tools 4.3.1



/**
 * DiasPago generated by hbm2java
 */
public class DiasPago  implements java.io.Serializable {


     private int id;
     private String fechaPago;

    public DiasPago() {
    }

	
    public DiasPago(int id) {
        this.id = id;
    }
    public DiasPago(int id, String fechaPago) {
       this.id = id;
       this.fechaPago = fechaPago;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(String fechaPago) {
        this.fechaPago = fechaPago;
    }




}


